# 1.Print 'Hello HCIA'.

In [1]:
print("Helo HCIA")

Helo HCIA


# 2.Define two variables and calculate their sum.

In [3]:
a=9;
b=4;
c=a+b;
print(c)

13


# 3.Define a list and replicate in three different ways.

In [5]:
a=[1,4,8,2];
b=[];
type(b);
c=[];
c.append(3);
c.append(2);
c.append('Hello world');
print(a);
print(b);
print(c)

[1, 4, 8, 2]
[]
[3, 2, 'Hello world']


# 4.Define two lists and merge them together.

In [6]:
a=[2,4,324,4];
b=[2132,213,123];
c=a+b;
print(c)

[2, 4, 324, 4, 2132, 213, 123]


# 5. Get the last element of the list and print it.

In [7]:
a=[12,213,2421,442,555555,];
a[-1]

555555

# 6.Define a tuple that contains only one element.

In [8]:
a = ('s', );
print(a)

('s',)


# 7.Define a three-line long string.

In [13]:
a=["n","f","g","k"];
b=["l","s"];
c=["d","f","f","w","o","s"];
dl = [len(a), len(b), len(c)];
if dl[0] > dl[1] and dl[0] > dl[2]: 
 print(a);
elif dl[1] > dl[0] and dl[1] > dl[2]: 
 print(b); 
else: 
 print(c)

['d', 'f', 'f', 'w', 'o', 's']


# 8.Define a tuple and then use the 'for loop' to print all the elements.

In [10]:
a=("hey","42","43","привет")
for x in a:
    print(x)

hey
42
43
привет


# 9.Define a function to do Multiplication, such as Mul(8,6),and its output 48.

In [15]:
def mul(a,b,c):
 return int(a)*int(b)*int(c);
print(mul(9,20,11))


1980


# 10.Import numpy and use numpy to define an array, the its shape  is (5,5) and all its elements is 0.

In [16]:
import numpy as np
a=np.zeros((5,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# 11.Import numpy and use numpy to define an array, the shape is (4,6) and all elements is 0.

In [17]:
import numpy as np
a=np.zeros((4,6))
print(a)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


# 12.Use numpy.arrange() to generate an array of shape(15,), then modify the shape to(3,5).

In [20]:
import numpy as np
a=np.arange(15,);
a=a.reshape(3,5);
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


# 13.Define two matrices, then calculate and print the result of their point multiplication.

In [21]:
import numpy as np
a=([2,3,8],[3,2,1],[3,7,0]);
b=([7,8,9],[9,2,1],[12,13,9]);
c=np.dot(a,b);
print(c)

[[137 126  93]
 [ 51  41  38]
 [ 84  38  34]]
